Repository lightspeeddevelopment/lsx-health-plan, pull requests merged in 2020-06, with the labels that each got.

#127 Added support for LSX color customizer.
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/lsx-health-plan.scss
  assets/css/scss/partials/_customizer-health-plan-body-colours.scss
  assets/css/scss/partials/_helpers.scss
  assets/css/scss/partials/_single-plan.scss
  assets/images/daily-plan.svg
  assets/images/download.svg
  assets/images/meal.svg
  changelog.md
  classes/class-frontend.php
Labels: [Priority] Normal, [Type] Enhancement

#128 Updating the exercise grid shortcode
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/partials/_shortcodes.scss
  assets/css/scss/partials/_single-plan.scss
  templates/partials/workout-grid.php
Labels: [Component] Shortcodes, [Component] Workouts, [Type] Enhancement

#129 Thumbnail sizes for all archive and shortcodes are improved.
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/partials/_shortcodes.scss
  assets/css/scss/partials/_single-plan.scss
  changelog.md
  includes/template-tags/exercise.php
  templates/content-archive-exercise.php
  templates/partials/workout-grid.php
  templates/partials/workout-list.php
Labels: [Type] Enhancement, [Type] Optimization

#132 Taxonomy ordering not working - Fix for #131
  classes/class-scpo-engine.php
Labels: [Component] Plans, [Priority] Critical, [Type] Bug
