Repository lightspeeddevelopment/lsx-health-plan, pull requests merged in 2020-05, with the labels that each got.

#93 Add/cover block support
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/partials/_single-plan.scss
  changelog.txt
  templates/page-template-my-plan.php
Labels: bug, enhancement

#97 Single Workout Tab - Layout Options
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/partials/_single-plan.scss
  changelog.txt
  lsx-health-plan.php
  readme.txt
  templates/partials/workout-grid.php
  templates/partials/workout-list.php
Labels: enhancement

#100 Exercise "Side" field and Refactoring of the Post Type class locations
  changelog.txt
  classes/class-core.php
  classes/class-post-type.php
  classes/post-types/class-downloads.php
  classes/post-types/class-exercise.php
  classes/post-types/class-meal.php
  classes/post-types/class-plan.php
  classes/post-types/class-recipe.php
  classes/post-types/class-tip.php
  classes/post-types/class-video.php
  classes/post-types/class-workout.php
  includes/template-tags.php
  includes/template-tags/exercise.php
  templates/content-archive-exercise.php
  templates/content-exercise.php
  templates/featured-exercise.php
Labels: enhancement

#101 Fix/99
  classes/class-integrations.php
  classes/integrations/class-download-monitor.php
  classes/integrations/class-lsx-search.php
  classes/integrations/class-woocommerce.php
  classes/integrations/class-wp-user-avatar.php
  includes/template-tags/exercise.php
  templates/partials/workout-grid.php
  templates/partials/workout-list.php
  vendor/lsx-field-post-search-ajax/cmb-field-post-search-ajax.php
Labels: bug

#103 - Removed the Style Hiding the Coupon WC Message
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/lsx-health-plan.min.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/lsx-health-plan.css
  assets/css/scss/partials/_helpers.scss
Labels: bug

#104 "View Cart" Message removed on Checkout.
  assets/css/maps/lsx-health-plan.css.map
  changelog.txt
  classes/integrations/class-woocommerce.php
Labels: bug, enhancement

#109 Add/88 - Exercise Slider Gallery
  assets/js/lsx-health-plan-slider.min.js
  assets/js/src/lsx-health-plan-slider.js
  classes/class-core.php
  classes/class-frontend.php
  classes/frontend/class-endpoints.php
  classes/frontend/class-gallery.php
  classes/frontend/class-modals.php
  includes/template-tags/exercise.php
  includes/template-tags/gallery.php
  templates/content-archive-exercise.php
  templates/content-exercise.php
  templates/partials/workout-grid.php
Labels: enhancement

#108 Fix/shortcode item
  classes/class-core.php
  classes/class-settings.php
  classes/class-setup.php
  includes/template-tags.php
Labels: bug, enhancement

#113 Fix/88+74
  assets/js/lsx-health-plan-modals.min.js
  assets/js/lsx-health-plan-slider.min.js
  assets/js/src/lsx-health-plan-modals.js
  assets/js/src/lsx-health-plan-slider.js
  classes/class-frontend.php
  classes/frontend/class-gallery.php
  includes/template-tags.php
  includes/template-tags/exercise.php
Labels: bug

#115 Add/112 - Workout tab settings
  changelog.txt
  classes/post-types/class-workout.php
  templates/partials/workout-grid.php
  templates/partials/workout-list.php
Labels: enhancement

#116 Single exercise view
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/_include-media.scss
  assets/css/scss/partials/_shortcodes.scss
  assets/css/scss/partials/_single-templates.scss
  includes/template-tags/exercise.php
  templates/content-exercise.php
Labels: enhancement

#117 Fix/shortcode template fixes
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/partials/_shortcodes.scss
  assets/css/scss/partials/_single-plan.scss
  includes/functions.php
  includes/shortcodes.php
  includes/template-tags.php
  templates/content-archive-recipe.php
  templates/content-archive-tip.php
  templates/featured-exercise.php
  templates/featured-tips.php
  templates/partials/content-shortcode-exercise.php
  templates/partials/meal-plans.php
  templates/partials/shortcode-loop.php
  templates/partials/workout-grid.php
  templates/partials/workout-sets.php
  templates/tab-content-meal.php
Labels: enhancement

#120 Added a template for the single workout pages.
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/partials/_shortcodes.scss
  assets/css/scss/partials/_single-plan.scss
  changelog.md
  classes/post-types/class-workout.php
  templates/partials/workout-grid.php
  templates/partials/workout-list.php
  templates/partials/workout-sets.php
  templates/partials/workout-table.php
  templates/single-workout.php
  templates/tab-content-workout.php
Labels: [Type] Enhancement

#125 Exercise Single page galleries and feature images
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/partials/_shortcodes.scss
  assets/css/scss/partials/_single-templates.scss
  changelog.md
  classes/frontend/class-gallery.php
  templates/content-exercise.php
Labels: [Component] Exercises, [Priority] Important, [Type] Enhancement

#126 Workout archive page
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/partials/_single-plan.scss
  classes/class-settings.php
  classes/post-types/class-workout.php
  templates/archive-workout.php
  templates/content-archive-workout.php
Labels: [Component] Workouts, [Type] Enhancement
