Repository lightspeeddevelopment/lsx-health-plan, pull requests merged in 2020-03, with the labels that each got.

#69 Pre and Post workout snack titles can be translated individually.
  changelog.txt
  languages/lsx-health-plan-en_EN.mo
  languages/lsx-health-plan-en_EN.po
  languages/lsx-health-plan.pot
  lsx-health-plan.php
Labels: bug

#71 - Adding in fix for Breadcrumb Translations #70
  changelog.txt
  classes/class-woocommerce.php
  lsx-health-plan.php
Labels: bug

#76 Checkout enhancements
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/partials/_helpers.scss
  assets/css/scss/partials/_woocommerce.scss
  assets/images/lets-encript.svg
  assets/images/payfast-footer-logo.svg
  assets/images/payment-logos-mobile.svg
  assets/images/payment-logos.svg
  changelog.txt
  classes/class-woocommerce.php
Labels: enhancement

#73 Fix/php errors
  changelog.txt
  includes/template-tags.php
  templates/archive-recipe.php
Labels: bug, enhancement

#78 Fix the lost password page, match demo to the design.
  assets/css/lsx-health-plan-rtl.css
  assets/css/lsx-health-plan.css
  assets/css/maps/lsx-health-plan.css.map
  assets/css/scss/partials/_woocommerce.scss
  changelog.txt
  includes/template-tags.php
  lsx-health-plan.php
Labels: bug, enhancement
